# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/prod-manifests" # Location of package manifests
    schedule:
      interval: "daily"
      time: "19:18"
      timezone: "Asia/Kolkata"
    allow:
      - dependency-type: "production"
    groups:
      prod-dependencies:
        patterns:
          - "*"
  # - package-ecosystem: "npm" # See documentation for possible values
  #   directory: "/dev-manifests" # Location of package manifests
  #   schedule:
  #     interval: "daily"
  #     time: "19:18"
  #     timezone: "Asia/Kolkata"
  #   allow:
  #     - dependency-type: "development"
  #   groups:
  #     dev-dependencies:
  #       patterns:
  #         - "*"
